version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  products:
    build: ./apps/products-service
    env_file: .env
    depends_on: [postgres]
    ports:
      - "3001:3001"

  orders:
    build: ./apps/orders-service
    env_file: .env
    depends_on: [postgres]
    ports:
      - "3002:3002"

  gateway:
    build: ./apps/gateway
    env_file: .env
    depends_on: [products, orders]
    ports:
      - "3000:3000"

volumes:
  pgdata:
